name: widgets
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: any
  google_fonts: any
  shared_preferences: ^2.2.1
  flutter_sticky_header: ^0.6.5
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.4 
  icons_launcher: ^2.1.4 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/

flutter_native_splash:
  color: "#2A323F"
  image: assets/icon4.png
  fullscreen: true
icons_launcher:
  image_path: "assets/logo.jpeg"
  platforms:
    android:
      enable: true
      image_path: "assets/logo.jpeg"
    ios:
      enable: true
      image_path: "assets/logo.jpeg"
   