name: widgets
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.7
  flutter_widget_from_html: ^0.14.6
  freezed_annotation: ^2.4.1
  get: any
  google_fonts: any
  intl: any
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  icons_launcher: ^2.1.4
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/

flutter_native_splash:
  color: "#2A323F"
  image: assets/icon4.png
  fullscreen: true
icons_launcher:
  image_path: "assets/logo.jpeg"
  platforms:
    android:
      enable: true
      image_path: "assets/logo.jpeg"
    ios:
      enable: true
      image_path: "assets/logo.jpeg"
