// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'actor.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ActorImpl _$$ActorImplFromJson(Map<String, dynamic> json) => _$ActorImpl(
      seqNo: json['seqNo'] as int?,
      type: json['type'] as String?,
      actNo: json['actNo'] as int?,
      nm: json['nm'] as String?,
      fiNm: json['fiNm'] as String?,
      bDt: json['bDt'] == null ? null : DateTime.parse(json['bDt'] as String),
      pNo: json['pNo'] as String?,
      sex: json['sex'] as String?,
      orgNo: json['orgNo'] as String?,
      ph: json['ph'] as String?,
      fax: json['fax'] as String?,
      mobPh: json['mobPh'] as String?,
      eMail: json['eMail'] as String?,
      web: json['web'] as String?,
      adType: json['adType'] as String?,
      note1: json['note1'],
      note2: json['note2'],
      startDt: json['startDt'] == null
          ? null
          : DateTime.parse(json['startDt'] as String),
      startCd: json['startCd'] as String?,
      endDt: json['endDt'],
      endCd: json['endCd'] as String?,
      payTerm: json['payTerm'] as int?,
      accNo: json['accNo'] as String?,
      disc: json['disc'] as int?,
      vatCd: json['vatCd'] as bool?,
      optInt1: json['optInt1'] as int?,
      optInt2: json['optInt2'] as int?,
      optInt3: json['optInt3'] as int?,
      optInt4: json['optInt4'] as int?,
      optInt5: json['optInt5'] as int?,
      optInt6: json['optInt6'] as int?,
      optInt7: json['optInt7'] as int?,
      optInt8: json['optInt8'] as int?,
      optInt9: json['optInt9'] as int?,
      optChar1: json['optChar1'] as String?,
      optChar2: json['optChar2'] as String?,
      optChar3: json['optChar3'] as String?,
      optChar4: json['optChar4'] as String?,
      optChar5: json['optChar5'] as String?,
      optChar6: json['optChar6'] as String?,
      optChar7: json['optChar7'] as String?,
      optChar8: json['optChar8'] as String?,
      optChar9: json['optChar9'] as String?,
      optBit1: json['optBit1'] as bool?,
      optBit2: json['optBit2'] as bool?,
      optBit3: json['optBit3'] as bool?,
      optBit4: json['optBit4'] as bool?,
      optBit5: json['optBit5'] as bool?,
      optBit6: json['optBit6'] as bool?,
      optLng1: json['optLng1'] as int?,
      optLng2: json['optLng2'] as int?,
      optLng3: json['optLng3'] as int?,
      optDate1: json['optDate1'] == null
          ? null
          : DateTime.parse(json['optDate1'] as String),
      county1: json['county1'] as String?,
      county2: json['county2'] as String?,
      actRel1: json['actRel1'] as int?,
      actRel2: json['actRel2'] as int?,
      actRel3: json['actRel3'] as int?,
      actRel4: json['actRel4'] as int?,
      actRel5: json['actRel5'] as int?,
      actRel6: json['actRel6'] as int?,
      actRel7: json['actRel7'] as int?,
      actRel8: json['actRel8'] as int?,
      actRel9: json['actRel9'] as int?,
      inf1: json['inf1'] as String?,
      inf2: json['inf2'] as String?,
      inf3: json['inf3'] as String?,
      webUsr: json['webUsr'] as String?,
      webSh: json['webSh'] as int?,
      crBy: json['crBy'] as String?,
      crDt:
          json['crDt'] == null ? null : DateTime.parse(json['crDt'] as String),
      chBy: json['chBy'] as String?,
      chDt:
          json['chDt'] == null ? null : DateTime.parse(json['chDt'] as String),
      pNoIsDNo: json['pNoIsDNo'] as bool?,
      avatarBase64: json['actPicture'] as String?,
    );

Map<String, dynamic> _$$ActorImplToJson(_$ActorImpl instance) =>
    <String, dynamic>{
      'seqNo': instance.seqNo,
      'type': instance.type,
      'actNo': instance.actNo,
      'nm': instance.nm,
      'fiNm': instance.fiNm,
      'bDt': instance.bDt?.toIso8601String(),
      'pNo': instance.pNo,
      'sex': instance.sex,
      'orgNo': instance.orgNo,
      'ph': instance.ph,
      'fax': instance.fax,
      'mobPh': instance.mobPh,
      'eMail': instance.eMail,
      'web': instance.web,
      'adType': instance.adType,
      'note1': instance.note1,
      'note2': instance.note2,
      'startDt': instance.startDt?.toIso8601String(),
      'startCd': instance.startCd,
      'endDt': instance.endDt,
      'endCd': instance.endCd,
      'payTerm': instance.payTerm,
      'accNo': instance.accNo,
      'disc': instance.disc,
      'vatCd': instance.vatCd,
      'optInt1': instance.optInt1,
      'optInt2': instance.optInt2,
      'optInt3': instance.optInt3,
      'optInt4': instance.optInt4,
      'optInt5': instance.optInt5,
      'optInt6': instance.optInt6,
      'optInt7': instance.optInt7,
      'optInt8': instance.optInt8,
      'optInt9': instance.optInt9,
      'optChar1': instance.optChar1,
      'optChar2': instance.optChar2,
      'optChar3': instance.optChar3,
      'optChar4': instance.optChar4,
      'optChar5': instance.optChar5,
      'optChar6': instance.optChar6,
      'optChar7': instance.optChar7,
      'optChar8': instance.optChar8,
      'optChar9': instance.optChar9,
      'optBit1': instance.optBit1,
      'optBit2': instance.optBit2,
      'optBit3': instance.optBit3,
      'optBit4': instance.optBit4,
      'optBit5': instance.optBit5,
      'optBit6': instance.optBit6,
      'optLng1': instance.optLng1,
      'optLng2': instance.optLng2,
      'optLng3': instance.optLng3,
      'optDate1': instance.optDate1?.toIso8601String(),
      'county1': instance.county1,
      'county2': instance.county2,
      'actRel1': instance.actRel1,
      'actRel2': instance.actRel2,
      'actRel3': instance.actRel3,
      'actRel4': instance.actRel4,
      'actRel5': instance.actRel5,
      'actRel6': instance.actRel6,
      'actRel7': instance.actRel7,
      'actRel8': instance.actRel8,
      'actRel9': instance.actRel9,
      'inf1': instance.inf1,
      'inf2': instance.inf2,
      'inf3': instance.inf3,
      'webUsr': instance.webUsr,
      'webSh': instance.webSh,
      'crBy': instance.crBy,
      'crDt': instance.crDt?.toIso8601String(),
      'chBy': instance.chBy,
      'chDt': instance.chDt?.toIso8601String(),
      'pNoIsDNo': instance.pNoIsDNo,
      'actPicture': instance.avatarBase64,
    };
